In [2]:
import pandas as pd
import re
import numpy as np

In [3]:
df = pd.read_csv('C:\\Users\\....\\Desktop\\FLV.csv')

In [4]:
df

,Unnamed: 0,Date,Time,Source IP address,Destination IP address,Bandwidth,Delay
0,0,892022,21516,192.168.1.3,52.85.221.134,55,0.000000
1,1,892022,21516,52.85.221.134,192.168.1.3,66,0.014674
2,2,892022,21516,2a02:587:7813:500:f0f7:f781:b084:7d42,2a00:1450:4001:80f::2004,75,0.000000
3,3,892022,21516,2a00:1450:4001:80f::2004,2a02:587:7813:500:f0f7:f781:b084:7d42,86,0.048090
4,4,892022,21518,192.168.1.3,116.202.225.117,55,0.000000
...,...,...,...,...,...,...,...
14944,14944,892022,22113,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.000063
14945,14945,892022,22113,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,2606:4700:4400::ac40:9aa3,74,0.000017
14946,14946,892022,22114,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.004248
14947,14947,892022,22114,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.024639
14948,14948,892022,22114,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,2606:4700:4400::ac40:9aa3,74,0.000123

In [5]:
df.set_index(['Source IP address', 'Destination IP address'])

                                                                             Unnamed: 0  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                                   0
52.85.221.134                         192.168.1.3                                     1
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004                        2
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42           3
192.168.1.3                           116.202.225.117                                 4
...                                                                                 ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       14944
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                   14945
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       14946
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       14947
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                   14948

                                                                               Date  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                          892022
52.85.221.134                         192.168.1.3                            892022
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004               892022
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42  892022
192.168.1.3                           116.202.225.117                        892022
...                                                                             ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  892022
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              892022
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  892022
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  892022
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              892022

                                                                              Time  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                          21516
52.85.221.134                         192.168.1.3                            21516
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004               21516
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42  21516
192.168.1.3                           116.202.225.117                        21518
...                                                                            ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  22113
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              22113
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  22114
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  22114
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              22114

                                                                             Bandwidth  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                                 55
52.85.221.134                         192.168.1.3                                   66
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004                      75
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42         86
192.168.1.3                           116.202.225.117                               55
...                                                                                ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       1434
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                     74
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       1434
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       1434
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                     74

                                                                                Delay
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                          0.000000
52.85.221.134                         192.168.1.3                            0.014674
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004               0.000000
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42  0.048090
192.168.1.3                           116.202.225.117                        0.000000
...                                                                               ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  0.000063
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              0.000017
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  0.004248
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  0.024639
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              0.000123

[14949 rows x 5 columns]

In [6]:
df.dtypes

Unnamed: 0                  int64
Date                        int64
Time                        int64
Source IP address          object
Destination IP address     object
Bandwidth                   int64
Delay                     float64
dtype: object

In [7]:
cols = ['Date','Time']
cols

['Date', 'Time']

In [8]:
df[cols] = df[cols].replace('[^\d.]','', regex = True).astype(int)

In [9]:
df[cols]

         Date   Time
0      892022  21516
1      892022  21516
2      892022  21516
3      892022  21516
4      892022  21518
...       ...    ...
14944  892022  22113
14945  892022  22113
14946  892022  22114
14947  892022  22114
14948  892022  22114

[14949 rows x 2 columns]

In [10]:
df

,Unnamed: 0,Date,Time,Source IP address,Destination IP address,Bandwidth,Delay
0,0,892022,21516,192.168.1.3,52.85.221.134,55,0.000000
1,1,892022,21516,52.85.221.134,192.168.1.3,66,0.014674
2,2,892022,21516,2a02:587:7813:500:f0f7:f781:b084:7d42,2a00:1450:4001:80f::2004,75,0.000000
3,3,892022,21516,2a00:1450:4001:80f::2004,2a02:587:7813:500:f0f7:f781:b084:7d42,86,0.048090
4,4,892022,21518,192.168.1.3,116.202.225.117,55,0.000000
...,...,...,...,...,...,...,...
14944,14944,892022,22113,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.000063
14945,14945,892022,22113,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,2606:4700:4400::ac40:9aa3,74,0.000017
14946,14946,892022,22114,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.004248
14947,14947,892022,22114,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.024639
14948,14948,892022,22114,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,2606:4700:4400::ac40:9aa3,74,0.000123

In [11]:
df.set_index(['Source IP address', 'Destination IP address'])

                                                                             Unnamed: 0  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                                   0
52.85.221.134                         192.168.1.3                                     1
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004                        2
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42           3
192.168.1.3                           116.202.225.117                                 4
...                                                                                 ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       14944
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                   14945
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       14946
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       14947
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                   14948

                                                                               Date  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                          892022
52.85.221.134                         192.168.1.3                            892022
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004               892022
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42  892022
192.168.1.3                           116.202.225.117                        892022
...                                                                             ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  892022
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              892022
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  892022
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  892022
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              892022

                                                                              Time  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                          21516
52.85.221.134                         192.168.1.3                            21516
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004               21516
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42  21516
192.168.1.3                           116.202.225.117                        21518
...                                                                            ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  22113
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              22113
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  22114
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  22114
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              22114

                                                                             Bandwidth  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                                 55
52.85.221.134                         192.168.1.3                                   66
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004                      75
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42         86
192.168.1.3                           116.202.225.117                               55
...                                                                                ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       1434
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                     74
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       1434
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       1434
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                     74

                                                                                Delay
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                          0.000000
52.85.221.134                         192.168.1.3                            0.014674
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004               0.000000
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42  0.048090
192.168.1.3                           116.202.225.117                        0.000000
...                                                                               ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  0.000063
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              0.000017
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  0.004248
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  0.024639
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              0.000123

[14949 rows x 5 columns]

In [12]:
df

,Unnamed: 0,Date,Time,Source IP address,Destination IP address,Bandwidth,Delay
0,0,892022,21516,192.168.1.3,52.85.221.134,55,0.000000
1,1,892022,21516,52.85.221.134,192.168.1.3,66,0.014674
2,2,892022,21516,2a02:587:7813:500:f0f7:f781:b084:7d42,2a00:1450:4001:80f::2004,75,0.000000
3,3,892022,21516,2a00:1450:4001:80f::2004,2a02:587:7813:500:f0f7:f781:b084:7d42,86,0.048090
4,4,892022,21518,192.168.1.3,116.202.225.117,55,0.000000
...,...,...,...,...,...,...,...
14944,14944,892022,22113,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.000063
14945,14945,892022,22113,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,2606:4700:4400::ac40:9aa3,74,0.000017
14946,14946,892022,22114,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.004248
14947,14947,892022,22114,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.024639
14948,14948,892022,22114,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,2606:4700:4400::ac40:9aa3,74,0.000123

In [13]:
import csv

In [14]:
df.to_csv('C:\\Users\\VasilisFermelis\\Desktop\\FLV.csv')

In [15]:
df

,Unnamed: 0,Date,Time,Source IP address,Destination IP address,Bandwidth,Delay
0,0,892022,21516,192.168.1.3,52.85.221.134,55,0.000000
1,1,892022,21516,52.85.221.134,192.168.1.3,66,0.014674
2,2,892022,21516,2a02:587:7813:500:f0f7:f781:b084:7d42,2a00:1450:4001:80f::2004,75,0.000000
3,3,892022,21516,2a00:1450:4001:80f::2004,2a02:587:7813:500:f0f7:f781:b084:7d42,86,0.048090
4,4,892022,21518,192.168.1.3,116.202.225.117,55,0.000000
...,...,...,...,...,...,...,...
14944,14944,892022,22113,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.000063
14945,14945,892022,22113,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,2606:4700:4400::ac40:9aa3,74,0.000017
14946,14946,892022,22114,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.004248
14947,14947,892022,22114,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.024639
14948,14948,892022,22114,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,2606:4700:4400::ac40:9aa3,74,0.000123

In [16]:
df.set_index(['Source IP address', 'Destination IP address'])

                                                                             Unnamed: 0  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                                   0
52.85.221.134                         192.168.1.3                                     1
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004                        2
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42           3
192.168.1.3                           116.202.225.117                                 4
...                                                                                 ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       14944
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                   14945
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       14946
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       14947
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                   14948

                                                                               Date  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                          892022
52.85.221.134                         192.168.1.3                            892022
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004               892022
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42  892022
192.168.1.3                           116.202.225.117                        892022
...                                                                             ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  892022
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              892022
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  892022
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  892022
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              892022

                                                                              Time  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                          21516
52.85.221.134                         192.168.1.3                            21516
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004               21516
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42  21516
192.168.1.3                           116.202.225.117                        21518
...                                                                            ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  22113
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              22113
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  22114
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  22114
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              22114

                                                                             Bandwidth  \
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                                 55
52.85.221.134                         192.168.1.3                                   66
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004                      75
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42         86
192.168.1.3                           116.202.225.117                               55
...                                                                                ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       1434
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                     74
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       1434
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb       1434
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3                     74

                                                                                Delay
Source IP address                     Destination IP address
192.168.1.3                           52.85.221.134                          0.000000
52.85.221.134                         192.168.1.3                            0.014674
2a02:587:7813:500:f0f7:f781:b084:7d42 2a00:1450:4001:80f::2004               0.000000
2a00:1450:4001:80f::2004              2a02:587:7813:500:f0f7:f781:b084:7d42  0.048090
192.168.1.3                           116.202.225.117                        0.000000
...                                                                               ...
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  0.000063
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              0.000017
2606:4700:4400::ac40:9aa3             2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  0.004248
                                      2a02:587:7813:500:b1f1:bd6e:afbb:bcbb  0.024639
2a02:587:7813:500:b1f1:bd6e:afbb:bcbb 2606:4700:4400::ac40:9aa3              0.000123

[14949 rows x 5 columns]

In [17]:
df.values

array([[0, 892022, 21516, ..., '52.85.221.134', 55, 0.0],
       [1, 892022, 21516, ..., '192.168.1.3', 66, 0.014674],
       [2, 892022, 21516, ..., '2a00:1450:4001:80f::2004', 75, 0.0],
       ...,
       [14946, 892022, 22114, ...,
        '2a02:587:7813:500:b1f1:bd6e:afbb:bcbb', 1434, 0.004248],
       [14947, 892022, 22114, ...,
        '2a02:587:7813:500:b1f1:bd6e:afbb:bcbb', 1434, 0.024639],
       [14948, 892022, 22114, ..., '2606:4700:4400::ac40:9aa3', 74,
        0.000123]], dtype=object)

In [18]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df

,Unnamed: 0,Date,Time,Source IP address,Destination IP address,Bandwidth,Delay
0,0,892022,21516,192.168.1.3,52.85.221.134,55,0.000000
1,1,892022,21516,52.85.221.134,192.168.1.3,66,0.014674
2,2,892022,21516,2a02:587:7813:500:f0f7:f781:b084:7d42,2a00:1450:4001:80f::2004,75,0.000000
3,3,892022,21516,2a00:1450:4001:80f::2004,2a02:587:7813:500:f0f7:f781:b084:7d42,86,0.048090
4,4,892022,21518,192.168.1.3,116.202.225.117,55,0.000000
...,...,...,...,...,...,...,...
14944,14944,892022,22113,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.000063
14945,14945,892022,22113,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,2606:4700:4400::ac40:9aa3,74,0.000017
14946,14946,892022,22114,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.004248
14947,14947,892022,22114,2606:4700:4400::ac40:9aa3,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,1434,0.024639
14948,14948,892022,22114,2a02:587:7813:500:b1f1:bd6e:afbb:bcbb,2606:4700:4400::ac40:9aa3,74,0.000123

In [36]:
from sklearn.model_selection import train_test_split
X = df.iloc[:,1:3]
y = df.iloc[:,6]
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.20)

In [37]:
y

0        0.000000
1        0.014674
2        0.000000
3        0.048090
4        0.000000
           ...
14944    0.000063
14945    0.000017
14946    0.004248
14947    0.024639
14948    0.000123
Name: Delay, Length: 14949, dtype: float64

In [38]:
batch_size = 128
epochs = 20
model = Sequential()
model.add(Dense(64, activation= "relu",input_shape=(2,)))
model.add(Dropout(0.2))
model.add(Dense(64, activation= "relu"))
model.add(Dropout(0.2))
model.add(Dense(1, activation= "linear"))
model.compile(loss= "mse", optimizer= "Adam")
hist=model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose =1, validation_split=(0.1))

Epoch 1/20
85/85 [==============================] - 1s 3ms/step - loss: 1010031424.0000 - val_loss: 1759596.6250
Epoch 2/20
85/85 [==============================] - 0s 2ms/step - loss: 98856160.0000 - val_loss: 2484955.0000
Epoch 3/20
85/85 [==============================] - 0s 2ms/step - loss: 28297828.0000 - val_loss: 148221.9062
Epoch 4/20
85/85 [==============================] - 0s 2ms/step - loss: 12216585.0000 - val_loss: 52829.7969
Epoch 5/20
85/85 [==============================] - 0s 3ms/step - loss: 6584663.0000 - val_loss: 18124.8750
Epoch 6/20
85/85 [==============================] - 0s 3ms/step - loss: 3894870.5000 - val_loss: 8577.7588
Epoch 7/20
85/85 [==============================] - 0s 3ms/step - loss: 2887191.7500 - val_loss: 5357.2397
Epoch 8/20
85/85 [==============================] - 0s 2ms/step - loss: 2412018.5000 - val_loss: 1674.9221
Epoch 9/20
85/85 [==============================] - 0s 2ms/step - loss: 1757929.8750 - val_loss: 903.2144
Epoch 10/20
85/85 [==============================] - 0s 2ms/step - loss: 1463277.2500 - val_loss: 29.7583
Epoch 11/20
85/85 [==============================] - 0s 2ms/step - loss: 1036949.8750 - val_loss: 314.9214
Epoch 12/20
85/85 [==============================] - 0s 2ms/step - loss: 845193.1250 - val_loss: 138.8206
Epoch 13/20
85/85 [==============================] - 0s 2ms/step - loss: 751518.1250 - val_loss: 339.8777
Epoch 14/20
85/85 [==============================] - 0s 2ms/step - loss: 552116.4375 - val_loss: 59.6686
Epoch 15/20
85/85 [==============================] - 0s 2ms/step - loss: 482201.1875 - val_loss: 68.2051
Epoch 16/20
85/85 [==============================] - 0s 2ms/step - loss: 497023.9375 - val_loss: 44.4499
Epoch 17/20
85/85 [==============================] - 0s 2ms/step - loss: 399198.8438 - val_loss: 39.1776
Epoch 18/20
85/85 [==============================] - 0s 2ms/step - loss: 320288.6562 - val_loss: 28.8076
Epoch 19/20
85/85 [==============================] - 0s 2ms/step - loss: 355492.9062 - val_loss: 25.0466
Epoch 20/20
85/85 [==============================] - 0s 2ms/step - loss: 307395.3438 - val_loss: 25.6162

In [39]:
new_sample = [[892022,21516]]
raw_output = model.predict(new_sample)

1/1 [==============================] - 0s 56ms/step

In [40]:
raw_output

array([[2.4990423]], dtype=float32)

In [81]:
df.isnull().sum()

Date                      0
Time                      0
Source IP address         0
Destination IP address    0
Bandwidth                 0
Delay                     0
dtype: int64